# -*- coding: utf-8 -*-
"""Sec2_Week1_Lab1_683380424-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IdoKcKLqHSg4le0bVy_pf8DiZOxZM8NP

Week 1 683380424-5 นาย ปฏิพัฒน์ หอทอง

Lab 1.1 Environment Setup & First Script
"""

print("Hello, Python Course!")

"""Lab 1.2 Working with Variables and Basic Data Types

2 declare and print valuebles
"""

Age = 19
grade = 3.42
Favorite_color = "Dark_Blue"
student = True

print("Age : ",Age,type(Age))
print("Greade : ",grade,type(grade))
print("Favorite Color : " ,Favorite_color, type(Favorite_color))
print("Student :  " ,student,type(student))

"""3 Perform simple arthimetic"""

num1 = 5
num2 = 10
sum = num1 + num2
dif = num1 - num2
pow = num1 * num2
div = num1 / num2
print("sum : ",sum)
print("dif : ",dif)
print("pow : ",pow)
print("div : ",div)

"""4 String concatenation and f-string"""

first_name = "Patipat"
last_name = "Horthong"
full_name = first_name + " " + last_name
print(f"Hello,{full_name}")

"""5 User input and type conservation"""

fav_num = int(input("enter favorite number : "))
print("Type of Favortie Number : ",type(fav_num))
result = fav_num + 5
print(" result is : ", result)

"""Activity 1.1 "Based on the introduction, where do you think scripting with Python could be applied in real-world scenarios? Think about tasks you do daily or things you've seen in other courses."

Answer : สามารถใช้ในการทำโจทย์คณิตศาสตร์เช่น การหาค่า 1-100 โดยใช้ for ในภาษา python

Activity 2 "Python Puzzlers" - Identifying Data Types & Output Format: Individual or pair work, followed by a class review. Instructions: Provide a set of small Python code snippets (on a handout or projected). For each snippet, students must: Predict the output. Identify the data type of specific variables after certain operations. Explain why they chose that output/data type.
"""

# Puzzler 1
x = 10
y = 3.5
z = x + y
print(z)
print(type(z))

"""ผลลัพธ์ :  z= 13.5 และ มี type เป็น float

เหตุผล : z=13.5 เพราะ 10 + 3.5 และเป็น type float เพราะเมื่อ int + float = float
"""

# Puzzler 2
name = "Alice"
age = "30" # Note: This is a string
message = name + " is " + age + " years old."
print(message)
print(type(age))

"""ผลลัพธ์ : message = " Alice is 30 year old." และ มี type เป้น String

เหตุผล : เพราะทุกตัวใน message เป็น type string และ age มี type เป็น string เพราะเครื่องหมาย " "
"""

# Puzzler 3
is_sunny = True
is_raining = False
print(is_sunny and is_raining)
print(type(is_sunny))

"""ผลลัพธ์ : ผลที่ออกมาจะเป็น false และ มี type เป็น boolean

เหตุผล : ที่ผลลัพธ์ออกมาเป็น False เพราะ and มีกรณีเดียวที่เป็น True คือ True and True  และ type เป็น boolean เพราะเราตั้งค่า is_sunny = True
"""

# Puzzler 4
# What happens here?
# num_str = input("Enter a number: ")
# result = num_str + 5
# print(result)

"""ผลลัพธ์ :  Error

เหตุผล : เพราะรับค่าเป็น String แล้วนำมาบวกกับ int ไม่สามารถทำได้ "10" + 5
"""